import { Metadata } from 'next';
import TripPlanner from '@/components/tools/TripPlanner';
import SchemaMarkup from '@/components/SchemaMarkup';
import { buildCtsPageMetadata } from '@/lib/seo-metadata';
import { getSiteUrl } from '@/lib/site';
import { migratedUnsplash } from '@/lib/site-media';

export async function generateMetadata(): Promise<Metadata> {
  return buildCtsPageMetadata({
    title: 'China Trip Planner | Personalized Itineraries for Your Style',
    description:
      'Plan your China trip with our interactive planner. Match duration, interests, budget, and season to recommended CTS tours, blog articles, and destination guides.',
    path: '/trip-planner',
    ogImagePath: migratedUnsplash('photo-1508804185872-d7badad00f7d'),
    keywords: ['trip planner', 'China itinerary', 'personalized tours', 'CTS Tours', 'China travel'],
    ogType: 'website',
  });
}

export default function TripPlannerPage() {
  const site = getSiteUrl();

  const webPageSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'China Trip Planner | Personalized Itineraries',
    description:
      'Interactive questionnaire to match New Zealand travellers with China tours, articles, and guides.',
    url: `${site}/trip-planner`,
    inLanguage: 'en-NZ',
    isPartOf: {
      '@type': 'WebSite',
      name: 'CTS Tours',
      url: site,
    },
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: site },
      { '@type': 'ListItem', position: 2, name: 'Travel tools', item: `${site}/travel-tools` },
      { '@type': 'ListItem', position: 3, name: 'Trip planner', item: `${site}/trip-planner` },
    ],
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'How does the China trip planner work?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'You choose trip length, interests, budget level, and preferred season. We score our China tours and surface blog posts and destination guides that align with your answers.',
        },
      },
      {
        '@type': 'Question',
        name: 'Are the tour recommendations personalised?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Recommendations are generated by matching your inputs to tour content, tier, and duration. For a fully bespoke itinerary, contact our team after reviewing the suggestions.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can I select more than one interest?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. You can select multiple interest themes such as history, nature, food, adventure, or relaxation to improve matching.',
        },
      },
      {
        '@type': 'Question',
        name: 'Does budget affect which tours appear?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Economy preferences favour Discovery and Stopover products, mid-range balances Discovery and Signature, and luxury emphasises Signature touring.',
        },
      },
      {
        '@type': 'Question',
        name: 'How many tours will I see?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'The planner shows up to three China tours that best fit your answers, plus related articles and guides.',
        },
      },
      {
        '@type': 'Question',
        name: 'What if I am flexible on travel dates?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Season selection helps prioritise content that mentions seasonal timing. You can rerun the planner with a different season or speak to CTS for flexible date options.',
        },
      },
      {
        '@type': 'Question',
        name: 'Are flights included in recommended tours?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Inclusions vary by product. Open any tour page for detailed inclusions and exclusions, or ask our consultants for flight-inclusive packaging.',
        },
      },
      {
        '@type': 'Question',
        name: 'Can families use this planner?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Yes. Choose interests that reflect your family, then review Discovery and Signature tours that include suitable pacing and highlights.',
        },
      },
      {
        '@type': 'Question',
        name: 'Where do blog and guide links go?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Blog links open CTS articles on china-travel topics. Guide links open our destination travel guides for deeper planning context.',
        },
      },
      {
        '@type': 'Question',
        name: 'How do I book after using the planner?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'Use the contact button to reach CTS for quotes and availability, or browse the recommended tour pages to send an enquiry.',
        },
      },
    ],
  };

  return (
    <>
      <SchemaMarkup data={[webPageSchema, breadcrumbSchema, faqSchema]} />
      <TripPlanner />
    </>
  );
}
